apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "cp-kafka.fullname" . }}-pdb
  labels:
    app: {{ template "cp-kafka.name" . }}
    chart: {{ template "cp-kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "cp-kafka.name" . }}
      release: {{ .Release.Name }}
  {{- if .Values.minAvailable }}
  minAvailable: {{ .Values.minAvailable }}
  {{- else }}
  maxUnavailable: 1
  {{- end }}
